//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH03_WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DuongDan { get; set; }
        public double Gia { get; set; }
        public string MoTa { get; set; }
        public string MaLoai { get; set; }
        public string MaSize { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual KichThuoc KichThuoc1 { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual Loai Loai1 { get; set; }
        public ICollection<SanPham> SPs { get; internal set; } = new List<SanPham>();
        public ICollection<SanPham> TSPs { get; internal set; } = new List<SanPham>();


    }
}
